apiVersion: apps/v1
kind: Deployment
metadata:
  name: car
  namespace: mycar
  labels:
    app: car
spec:
  replicas: 1
  selector:
    matchLabels:
      app: car
  template:
    metadata:
      labels:
        app: car
    spec:
      containers:
        - name: car
          image: 740569282574.dkr.ecr.ap-northeast-1.amazonaws.com/car:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: v1
kind: Service
metadata:
  name: car
  namespace: mycar
  labels:
    app: car
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: car
